spring:
  main:
    web-application-type: none

etl:
  recipenlg:
    csv-path: /home/milmanart/fitapp-backend/dataset/full_dataset.csv
    top-dishes: 2000
    min-recipes-per-dish: 30
    min-ingredient-support: 0.3
    max-ingredients: 8
    default-serving-g: 300
    truncate: true
    dry-run: false

logging:
  level:
    root: INFO
    pl.fitapp.backend.etl: DEBUG
